export const NOTIFICATION_TYPES = {
  PRAYER: 'PRAYER',
  AMEN: 'AMEN',
  COMMENT: 'COMMENT',
  FOLLOW: 'FOLLOW',
  GROUP_INVITE: 'GROUP_INVITE',
  GROUP_JOIN: 'GROUP_JOIN',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  ADMIN: 'ADMIN',
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

export const DEFAULT_NOTIFICATION_TYPE = NOTIFICATION_TYPES.PRAYER;
